# Generated by Django 5.2.6 on 2025-10-08 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={},
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='usuario',
        ),
        migrations.AddField(
            model_name='transaccion',
            name='destino',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='categoria',
            field=models.CharField(choices=[('Comida', 'Comida'), ('Salario', 'Salario'), ('Compras', 'Compras'), ('Transferencias', 'Transferencias'), ('Servicios', 'Servicios'), ('Otros', 'Otros')], default='Otros', max_length=50),
        ),
    ]
