# Generated by Django 5.2.6 on 2025-11-26 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0003_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaccion',
            name='categoria',
            field=models.CharField(choices=[('Comida', 'comida'), ('Salario', 'salario'), ('Compras', 'compras'), ('Transferencias', 'transferencias'), ('Servicios', 'servicios'), ('Ventas', 'ventas'), ('Otros', 'otros')], default='Otros', max_length=50),
        ),
    ]
