# Generated by Django 5.2.6 on 2026-01-14 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0006_notificacion_leido'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='bloqueo_ia_hasta',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='strikes_no_transaccion',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
